services:
  web:
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    env_file: .env
    restart: always

  php:
    build: .
    volumes:
      - ./src:/src
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mariadb
    env_file: .env
    command: ["php-fpm"]
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: sortea_mariadb
    env_file: .env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./config/db/.my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8181:80"
    restart: always